name: mek_assets
description: Automatically generate dart classes / flutter pubspec entries for your assets files.
version: 3.0.0-dev.0
homepage: https://github.com/BreX900/mek_assets
topics:
  - assets
  - assets-generator
  - code-gen

environment:
  sdk: '>=3.8.0 <4.0.0'

scripts:
  publish: dart pub publish
  # To generate .g files:
  generate-code: dart run build_runner watch --delete-conflicting-outputs

dependencies:
  args: ^2.7.0
  checked_yaml: ^2.0.3
  cli_util: ^0.4.2

  path: ^1.9.1
  code_builder: ^4.10.0
  dart_style: ^3.0.0
  collection: ^1.17.2
  recase: ^4.1.0
  pub_semver: ^2.2.0
  json_annotation: ^4.9.0

  build: ^4.0.0
  glob: ^2.1.0

dev_dependencies:
  mek_lints: ^4.0.0
#  test: ^1.23.1

  # To generate .g files:
  # dart run build_runner build --delete-conflicting-outputs
  # dart run build_runner watch --delete-conflicting-outputs
  build_runner: ^2.10.1
  json_serializable: ^6.8.0

